language: node_js
sudo: false
dist: trusty
node_js: '9'
cache:
  directories:
    - node_modules
script:
  - npm install codecov -g
  - npm run test
  - npm run check-coverage
after_success:
  - codecov
  # - npm run semantic-release
